### PR TITLE
Allow use of Babel experimental stages

### PR DESCRIPTION
**Pull request by murphyrandle**
This pull request allows optional use of Babel's experimental stages

### CODE REVIEW

**Comment by sebmck** [comment]
Seems like a slippery slope with supporting options via environment flags. I'd much rather something like #2 happen. But in the meantime I guess I can merge this, just beware that it may change in the near future.

**Comment by sebmck** [comment]
Available as of 5.0.1

**Comment by sgwilym** [comment]
Thanks for this. Just one question, though: how do I get Jest to include the babel runtime during testing? I keep bumping into `rengeratorRuntime is not defined`.

**Comment by sebmck** [comment]
@sgwilym `require("babel/polyfill")` should work.

**Comment by sgwilym** [comment]
It's not an easy life being a twit. Cheers!

**Pull request merged**
