### PR TITLE
Updated to use presets

### PR DESCRIPTION
**Pull request by mikevalstar**
Presets are required to get compiling in babel now.

### CODE REVIEW

**Comment by pnuzhdin** [comment]
Don't like hardcoded presets. Why you don't want to specify them in .babelrc?

**Comment by homer0** [comment]
I don't like hardcoded presets either, but I also don't like that I have to create `.babelrc` just for that (I build with Browserify and I'm sending the presets on the the transformer). Isn't there a middle ground?

**Comment by mikevalstar** [comment]
I think a good middle ground will be adding support in Jest to add params to the transformer.  I will look into writing this this weekend and see if I can get that approved by their team.

**Comment by homer0** [comment]
@mikevalstar that would be great, something like a `scriptPreprocessorSettings`, and it wouldn't be helpful just for this, but we could fix things like #51 without the need of a new release (or a fork).

**Comment by mikevalstar** [comment]
Looks like its already built in but not utilized.  I'll have to leave #51 to you (not quire sure what you need to do for that ;), but I'm fixing it up now.

**Comment by mikevalstar** [comment]
Ok, so assuming the Jest team is good with my other pull request, you will be able to send in any options to the babel transformer that you would be able to send into the regular babel-core

**Comment by homer0** [comment]
@mikevalstar awesome :smile: ! And regarding #51, the `istanbul ignore next` comment was removed, so the coverage report includes the babel code, but it shouldn't.

**Comment by cpojer** [comment]
This can be solved by using a `.babelrc` file. If you don't like using a babelrc file, please use your own preprocessor. See https://github.com/facebook/fbjs/blob/master/scripts/jest/preprocessor.js for an example.

**Pull request closed without merging**
